// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwKWy6A70NE43rpVqFluElJ4hoGjYBp_8',
    appId: '1:779959424131:web:1959c097950681855db7b6',
    messagingSenderId: '779959424131',
    projectId: 'fir-example-3a0c8',
    authDomain: 'fir-example-3a0c8.firebaseapp.com',
    storageBucket: 'fir-example-3a0c8.firebasestorage.app',
    measurementId: 'G-WSBWTYDM52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeBDyUm8uXldJPtpkZcsLIaoOUrdcRmzo',
    appId: '1:779959424131:android:ded0cc9f6e42754d5db7b6',
    messagingSenderId: '779959424131',
    projectId: 'fir-example-3a0c8',
    storageBucket: 'fir-example-3a0c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYxyWtYcte5pSMJQcla_hjbQdQbP-LQ0',
    appId: '1:779959424131:ios:04721a067a5dc9b25db7b6',
    messagingSenderId: '779959424131',
    projectId: 'fir-example-3a0c8',
    storageBucket: 'fir-example-3a0c8.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYxyWtYcte5pSMJQcla_hjbQdQbP-LQ0',
    appId: '1:779959424131:ios:04721a067a5dc9b25db7b6',
    messagingSenderId: '779959424131',
    projectId: 'fir-example-3a0c8',
    storageBucket: 'fir-example-3a0c8.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwKWy6A70NE43rpVqFluElJ4hoGjYBp_8',
    appId: '1:779959424131:web:ea51eea25ad5d6565db7b6',
    messagingSenderId: '779959424131',
    projectId: 'fir-example-3a0c8',
    authDomain: 'fir-example-3a0c8.firebaseapp.com',
    storageBucket: 'fir-example-3a0c8.firebasestorage.app',
    measurementId: 'G-535ZJ2KYS1',
  );
}
